# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast ICM Log-likelihood Computation using Eigen (Fixed Version)
#'
#' Computes the log-likelihood for a single curve using precomputed cache from
#' .build_icm_cache(). Uses simplified Eigen operations to avoid compilation warnings.
#'
#' @param yresid Matrix of residuals (P x M) where P is number of time points and M is number of channels
#' @param Uxx Eigenvectors from kernel eigendecomposition (P x P)
#' @param chollist List of Cholesky factors for each eigenvalue block
#' @param logdetsum Sum of log determinants for likelihood computation
#'
#' @return Numeric scalar representing the log-likelihood value
fast_icm_loglik_curve_eigen <- function(yresid, Uxx, chollist, logdetsum) {
    .Call('_WICMAD_fast_icm_loglik_curve_eigen', PACKAGE = 'WICMAD', yresid, Uxx, chollist, logdetsum)
}

#' Batch Fast ICM Log-likelihood Computation (Fixed Version)
#'
#' Computes log-likelihoods for multiple curves in a single C++ call for better performance.
#'
#' @param curves List of residual curve matrices
#' @param Uxx Eigenvectors from kernel eigendecomposition (P x P)
#' @param chollist List of Cholesky factors for each eigenvalue block
#' @param logdetsum Sum of log determinants for likelihood computation
#'
#' @return Numeric vector of log-likelihood values
fast_icm_loglik_curves_batch <- function(curves, Uxx, chollist, logdetsum) {
    .Call('_WICMAD_fast_icm_loglik_curves_batch', PACKAGE = 'WICMAD', curves, Uxx, chollist, logdetsum)
}

fast_wavelet_forward_1d <- function(x, wf = "la8", J = 4L, boundary = "periodic") {
    .Call('_WICMAD_fast_wavelet_forward_1d', PACKAGE = 'WICMAD', x, wf, J, boundary)
}

fast_wavelet_inverse_1d <- function(coeff, map) {
    .Call('_WICMAD_fast_wavelet_inverse_1d', PACKAGE = 'WICMAD', coeff, map)
}

